### ISSUE TITLE
Impossible to start the application

### ISSUE THREAD

**Issue by go-ten** [flathub/org.gnome.Podcasts#8]
Hi,

When I run the application I get the error message:

> flatpak run org.gnome.Podcasts 
Unable to init server: Impossible de se connecter : Connexion refusée
thread 'main' panicked at 'Error initializing gtk.: BoolError { message: "Failed to initialize GTK", filename: "/run/build/gnome-podcasts/vendor/gtk/src/rt.rs", function: "gtk::rt", line: 102 }', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Regards

**Comment by alatiera** [comment]
Looks like gtk is failing to initialize for whatever reason. Could you provide some information about your system? Distribution, flatpak version, xdg-portals version, display server, xorg/wayland etc, etc?

**Comment by go-ten** [comment]
yes :
Debian 10 Buster on X11
Flatpak 1.2.5 (from Stable Proposed Update)
GTK Theme : Adapta.

I would like to mention that this application has always worked for me. Only for a few days it doesn't start

**Comment by go-ten** [comment]
There's no problem on Wayland.

**Comment by alatiera** [comment]
Can you see if the issue still exists with the latest update by a chance? Should roll out in an hour or two.
